systemwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from appsystem.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('sign-up/', sign_up.as_view(), name='sign_up'),
    path('deconnexion/', deconnexion, name='Deconnexion'),
    path('', include('django.contrib.auth.urls')),

    path('search/', recherche, name='search'),
    path('system/', system_list, name='system_list'),
    path('system/add/', system_add, name='system_add'),
    path('system/<int:system_id>/', system_details, name='system_details'),
    path('celestial/', celestial_list, name='celestial_list'),
    path('choices/add/',choices_add, name='choices_add'),
    path('celestial/add/', celestial_add, name='celestial_add'),
    path('celestialtypes/add', celestialtype_add, name='celestialtype_add'),

    path('systems/', systems_index, name='systems'),
    path('systems/<int:system_id>/', systems_show, name='systems'),
    path('systems/new/', systems_new, name='new_system'),
    path('systems/create/', create_system, name='create_system'),
    path('astronomical_bodies/', astronomical_bodies_index, name='astronomical_bodies'),
    path('astronomical_bodies/<int:astronomical_body_id>/', astronomical_bodies_show, name='astronomical_bodies')
]

appsystem/models.py
from django.db import models


# Cette table permet de faire référence au système auquel appartient les corps ainsi que les différents systèmes
class System(models.Model):
    # Ce champ est la clé étrangère qui pointe vers l'id du système parent de la table système
    name = models.TextField(null=True)
    image = models.ImageField(null=True)
    allegiance = models.TextField(null=True)
    coordinates = models.TextField(null=True)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True)
    population = models.IntegerField(null=True)
    ground_distance = models.IntegerField(null=True)
    state = models.TextField(null=True)
    economy = models.TextField(null=True)
    faction = models.TextField(null=True)
    security = models.TextField(null=True)
    government = models.TextField(null=True)

    def astronomical_bodies(self):
        return Celestial.objects.filter(fk_system_origine=self.id)

    def astronomical_bodies_count(self):
        return Celestial.objects.filter(fk_system_origine=self.id).count()

    def sub_systems(self):
        return System.objects.filter(parent_id=self.id)

    def sub_systems_count(self):
        return System.objects.filter(parent_id=self.id).count()

    def __str__(self):
        return f"{self.name}"

    # définition des variable à choix multiple

    # ALLEGEANCE_CHOICES = (
    # (1, ('Fédération')),
    # (2 ('Alliance')),
    # (3, ('Empire')),
    # (4, ('Indépendant')),
    # )

    # GOUVERNEMENT_CHOICES = (
    # (5, ('Anarchie')),
    # (6, ('Impériale')),
    # (7, ('Patronage')),
    # (8, ('Colonie pénitentiaire')),
    # (9, ('Théocratie')),
    # (10, ('Colonie')),
    # (11, ('Communisme')),
    # (12, ('Confédération')),
    # (13, ('Coopérative')),
    # (14, ('Entreprise')),
    # (15, ('Démocratie')),
    # (16, ('Dictature')),
    # (17, ('Féodal')),
    # )

    # nom = models.CharField(max_length=100)
    # coordonnes = models.IntegerField()

    # établissement du choix multiple
    # allegeance = MultiSelectField(
    # title=models.CharField(max_length=200),
    # choices=ALLEGEANCE_CHOICES,
    # default=4,
    # max_choices=1,
    # )

    # def __str__(self):
    # return self.allegeance

    # établissement du choix multiple

    # gouvernement = MultiSelectField(
    # title=models.CharField(max_length=200),
    # choices=GOUVERNEMENT_CHOICES,
    # default=14,
    # max_choices=1,
    # )

    # def __unicode__(self):
    # return self.__str__()


# Table des types de corps
class CelestialType(models.Model):
    Nom = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.Nom}"


# Table des corps célestes
class Celestial(models.Model):
    # Ce champ indique à quel système (le plus petit possible) le corps appartient, dans la table "system"
    # system = models.ForeignKey(System, on_delete=models.CASCADE, blank=True, null=True)
    fk_system_origine = models.ForeignKey(System, on_delete=models.CASCADE, related_name="emplacement", blank=True,
                                          null=True)
    # Ce champ indique à quel type de corps le corps correspond, dans la table "type"
    fk_type = models.ForeignKey(CelestialType, on_delete=models.CASCADE, related_name="type", blank=True, null=True)
    nom = models.TextField(null=True)
    distance_au_sol = models.IntegerField()
    masse = models.IntegerField()
    rayon = models.IntegerField()
    gravite = models.IntegerField()
    temperature = models.IntegerField()
    volcanisme = models.TextField(null=True)
    atmosphere = models.TextField(null=True)
    composition = models.TextField(null=True)
    period_orbital = models.IntegerField()
    inclinaison_orbital = models.IntegerField()
    station = models.TextField(null=True)
    distance = models.IntegerField()

    def name(self):
        return self.nom

    def system(self):
        return self.fk_system_origine

    def __str__(self):
        return f"{self.nom}"

appsystem/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import logout, authenticate, login
from appsystem.form import *
from appsystem.models import System, CelestialType
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


# Fonction utilisee pour verifier l'etat de connection d'un utilisateur. Utilisee par toutes les autres fonctions
def connect(request):
    adm = 0  # Compte administrateur
    connecte = 0  # Connecte
    username = 0  # id de l'utilisateur
    if request.session.__contains__('appsystem_connect_state') == True:
        if request.session['appsystem_connect_state'] == True:  # si l'utilisateur est connecte
            connecte = 1

            username = User.objects.get(username=request.session['appsystem_user'])
            if str(username.admin) == str(1):
                adm = 1

    return ({"connecte": connecte, "adm": adm, "username": username})


def recherche(request) :
    Celest = Celestial.objects.all()
    Syst = System.objects.all()
    return render (request, 'Templates/search.html', {"Celest" : Celest, 'Syst': Syst})


def system_add(request):
    if request.user.is_authenticated:
        form = SystemForm()
        return render(request, 'templates/system_add.html', {"form": form})
    else:
        return redirect('login')


def celestial_add(request):  # Fonctionne (normalement)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CelestialForm(request.POST or None)

            if form.is_valid():
                form.save()
                return redirect('system_list')

        form = CelestialForm()
        return render(request, 'templates/celestial_add.html', {'form': form})
    else:
        return redirect('login')


def home(request):
    return render(request, "templates/home.html", {})


def search(request):
    return render(request, "templates/search.html", {})


def system_list(request):
    if request.method == 'POST':
        form = SystemForm(request.POST or None)

        if form.is_valid():
            new_system = System()
            new_system.name = form.cleaned_data['name']
            #new_system.image = form.cleaned_data['image']
            new_system.allegiance = form.cleaned_data['allegiance']
            new_system.coordinates = form.cleaned_data['coordinates']
            new_system.population = int(form.cleaned_data['population'])
            new_system.ground_distance = int(form.cleaned_data['ground_distance'])
            new_system.state = form.cleaned_data['state']
            new_system.economy = form.cleaned_data['economy']
            new_system.faction = form.cleaned_data['faction']
            new_system.security = form.cleaned_data['security']
            new_system.government = form.cleaned_data['government']
            new_system.save()

    systems = System.objects.all()
    return render(request, "templates/system_list.html", {'systems': systems})


def system_details(request, system_id):
    system = System.objects.get(pk=system_id)
    return render(request, 'templates/system_details.html', {'system': system})


def celestial_list(request):
    return render(request, "templates/system_details.html", {})


def celestialtype_add(request):  # Fonctionne
    if request.user.is_authenticated:
        typ = CelestialType.objects.all()  # Pour afficher la liste des types déjà présents dans la table
        form_type = TypeForm()
        return render(request, 'templates/celestialtypes_add.html', {"types": typ, 'form': form_type})
    else:
        return redirect('login')


# Connexion utilisateur
def sign_in(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(request, username=username, password=password)

    if user is not None:
        login(request, user)
        return redirect('system_list')
    else:
        return render(request, "templates/login.html", {})


# Creation d'un compte utilisateur + authentification
class sign_up(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/sign_up.html'

def deconnexion(request):
    request.session['appsystem_connect_state']=False
    return render (request,"templates/deconnexion.html")


###########
## Controller methods for Systems

def systems_index(request):
    systems = System.objects.all()
    return render(  request,
                    "templates/systems/index.html",
                    { 'systems': systems }   )


def systems_show(request, system_id):
    system = get_object_or_404(System, pk=system_id)
    return render(  request,
                    'templates/systems/show.html',
                    { 'system': system }    )


def systems_new(request):
    system_form = SystemForm()
    return render(request, 'templates/systems/new.html',
                  {"system_form": system_form})


def create_system(request):
    if request.method == 'POST':
        system = SystemForm(request.POST)
        if system.is_valid():
            system.save()
    else:
        system = SystemForm

    return render(  request,
                    'templates/home.html',
                    { 'system_form': system }  )


###########
## Controller methods for Astronomical Bodies
def astronomical_bodies_index(request):
    astronomical_bodies = Celestial.objects.all()
    return render(  request,
                    "templates/astronomical_bodies/system_list.html",
                    { 'astronomical_bodies': astronomical_bodies }   )


def astronomical_bodies_show(request, astronomical_body_id):
    astronomical_body = get_object_or_404(Celestial, pk=astronomical_body_id)
    return render(  request,
                    'templates/astronomical_bodies/show.html',
                    { 'astronomical_body': astronomical_body }    )


def choices_add(request):
    return render(request, "templates/choices_add.html", {})

appsystem/templates/_placeholdercadre.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'connexion.css' %}" />
	<title>compte</title> <!-- nom de la page qui apparait ds l'onglet-->
</head>



<body>

	<center><header> <!--logo MNHN, SU et logo de notre site éventuellement-->
		<table>
			<tr>
			<td>
				<a href=https://www.mnhn.fr/fr/etudiants><img src="{%static 'logoMNHN.png' %}" alt="logo du MNHN" height=100px/></a>
			</td>
			<td>
				<center><h2>Bienvenue </br>sur </br>Elite Dangerous </h2></center>
			</td>
			<td>
				<a href=http://sciences.sorbonne-universite.fr/fr/index.html><img src="{%static 'logoSU.png' %}" alt="logo de SU" height=90px/></a>
			</td>
			</tr>
		</table>
		<hr/>
	</header></center>


	<main>

{% block body %}

{% endblock %}
	</main>

appsystem/templates/celestial_add.html
{% extends 'system_list.html' %}
{% load static %}

{% block contenu %}

    <div class="celestialadd">
        <h1>Renseignez de nouveau astres et/ ou étoiles</h1>
    </div>

    <div id="Form">
        <form method="POST">
            <fieldset>
                <legend>Astres et/ ou étoiles</legend>
                {% csrf_token %}
                {% for a in form %}
                    <div class="fieldWrapper">
                        {{ a.errors }}
                        {{ a.label_tag }} {{ a }}
                    </div>
                {% endfor %}
            </fieldset>
            <p><input type="submit" value="Valider"/></p>
        </form>
    </div>
{% endblock %}

appsystem/templates/celestialtypes_add.html
{% extends 'system_list.html' %}


{% block contenu %}
						 <h1>Renseignez des types de corps célestes</h1>

						<div id="Form"> 

							<form action="{% url 'ValiderType' %}" method="POST">
									{%csrf_token%}
									{{form}}
							<p><input type="submit"value="Valider" /></p>
						</form>
						</div>
						<div id='affichages types'>
						<p><h2>Types déjà existants dans la base de données</h2></p>
							{%for n in types%}
								{{n.Nom}}</br>
							{%endfor%}
						</div>
{% endblock %}

appsystem/templates/choices_add.html
{% extends 'system_list.html' %}
{% load static %}

{% block contenu %}
    <div id="choices">
<center>
    <table>
        <tr>
            <td> <a href="{% url 'system_add' %}"><img src="{% static 'addsystem.jpg' %}" alt="" class="arrondie"/></a></td>
            <td><a href="{% url 'celestial_add' %}"><img src="{% static 'addcelestial.jpg' %}" alt="" class="arrondie"/></a></td>
        </tr>
        <tr>
            <td>Ajouter un système</td>
            <td>Ajouter un corps céleste</td>
        </tr>
    </table>


</center>
    </div>
{% endblock %}

appsystem/templates/creation_util.html
{% extends 'system_list.html' %}

{% block contenu %}
						 <h1>Créez votre compte</h1>
						<div id="Form"> 
							<form action={%url 'Valider_crea' %} method="POST">

							{% csrf_token %}
							
							<h3>Choisissez un nom d'utilisateur :</h3>
							{{ form.username }} 
							
							</br></br>

							<h3>Choisissez un mot de passe :</h3>
							{{ form.mdp }}
							
							</br></br>

							<p><font color="red">{{message}}</font></p>
							
							<input type='submit' class='Envoyer'>
							</form>
						</div>
{% endblock %}

appsystem/templates/home.html
{% load static %}

<html lang="">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'cssacceuil.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'javaacceuil.js' %}"/>
    <meta charset="utf-8"/>
    <title>Elite Dangerous System </title>
</head>

<body>
<div id="bloc_page">
    <header></header>

    <div id="contenu" align="center">

        <div class="big-circles">
            <div class="big-circle"></div>
            <div class="big-circle"></div>
            <div class="big-circle"></div>
        </div>

        <section id="home">
            <div class="slide-wrapper">
                <div class="smallcircles">
                    <div class="small-circle"></div>
                    <div class="small-circle"></div>

                </div>

                <div class="cover-wrapper text-center" id="home-content">
                    <div class="cover-wrapper__inner">
                        <div class="cover-wrapper__container">
                            <h1>Elite Dangerous System</h1>
                            <p>
                                <a class="btn btn-cta btn-cta__green text-uppercase trigger" href="{% url 'system_list' %}">cliquer sur la page</a>
                            </p>

                            <a href="{% url 'login' %}">Connexion</a>
                            <a href="{% url 'sign_up' %}">Créer un compte</a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>
</body>
</html>

appsystem/templates/layout.html
{% load static %}
{% load staticfiles %}

<html>
	<head>
		<link rel="stylesheet" type="text/css" href="{% static 'css.css' %}" />
		<meta charset="utf-8" />
	  <title>Elite Dangerous System</title>
	</head>

	<body>
		{% block header %}
			<header>
				<div id="logo">
				    <a href="{% url 'home' %}"><img src="{% static 'elite.png' %}" alt="" /></a>
				</div>
			</header>
		{% endblock %}

    <main>
  		{% block content %}
        Content
  		{% endblock %}
    </main>

		{% block footer %}
            <footer>
             <div id="colum.side">
     <table>
         <tr>
             <td><a href="{% url 'search' %}"><img src="{% static 'loupe.png' %}" alt=""></a></td>
         </tr>
         <tr>
             <td><a href="{% url 'choices_add' %}"><img src="{% static 'ajout.png' %}" alt=""></a></td>
         </tr>
     </table>
 </div>
 <footer>
    <table id="icones" style="margin: 0 auto;">
        <tr>
            <td align="center">
                <figure >
                    <a href ="https://www.facebook.com/EliteDangerousOfficial/?ref=page_internal"><img src="{% static 'facebook.png' %}" alt="Facebook" class="facebook" /></a>
                </figure>
            </td>

            <td align="center">
                <figure >
                    <a href ="https://www.instagram.com/elite.dangerous/"><img src="{% static 'insta.png' %}" alt="Instagram" href="#" class="instagram"/></a>
                </figure>
            </td>

            <td align="center">
                <figure>
                    <a href ="https://forums.frontier.co.uk/showthread.php/164176-GalNet-RSS-Feed"><img src="{% static 'rss.png' %}" alt="RSS" href="#" class="rss"/></a>
                </figure>
            </td>
        </tr>
    </table>
     <br></br>
		<center><div id="connexion">
            <a href="{% url 'login' %}">Connexion</a>
            <a href="{% url 'sign_up' %}">Créer un compte</a>
            <a href="{% url 'deconnexion' %}">déconnexion</a>
        </div></center>
     <p id="bas">MNHN Company</p>
</footer>
		{% endblock %}
	</body>
</html>

appsystem/templates/search.html
{% extends 'system_list.html' %}
{% load staticfiles %}

{% block contenu %}
    <div class="bar">
        <h1>Recherche avancée</h1>
    <form class="searchform group">
 <label for="search-box">
    <img src="{% static 'search.png' %}" alt="">

<input type="text" id="Rech" onkeyup="Fonction()" placeholder="Recherche par nom" title="Taper un nom"/>

<ul id="Liste">
<br></br>
    <p><h3>Systèmes</h3></p>
	{% for t in Syst %}
        <li><a href="../systems/{{t.id}}/">{{t.name}}</a></li>
	{% endfor %}
    <p><h3>Corps célestes</h3></p>
    {% for i in Celest %}
        <li>{{i.nom}}</li>
    {% endfor %}
</ul>
<script>
function Fonction() {
    var input, filter, ul, li, a, i, txtValue;
    input = document.getElementById("Rech");
    filter = input.value.toUpperCase();
    ul = document.getElementById("Liste");
    li = ul.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        a = li[i].getElementsByTagName("a")[0];
        txtValue = a.textContent || a.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
</script>
 </label>
    </div>
{% endblock %}

appsystem/templates/system_add.html
{% extends 'system_list.html' %}

{% block contenu %}

    <!-- Ne veut pas me prendre mon lo? -->
    <div id="System">
        <center><h1>Renseignez une nouveau système</h1></center>
    </div>

    <div id="Form">
        <form action="{% url 'system_list' %}" method="POST">
            <fieldset>
                <legend>Système</legend>
                <br></br>
                {% csrf_token %}
                {% for s in form %}
                    <div class="fieldWrapper">
                        {{ s.errors }}
                        {{ s.label_tag }} {{ s }}
                    </div>
                {% endfor %}
            </fieldset>
            <p><input type="submit" value="Valider"/></p>
        </form>
    </div>

{% endblock %}

appsystem/templates/system_details.html
{% load staticfiles %}

<div id="logo">
    <img src="{% static 'elite.png' %}" alt="">
</div>

{{ system.name }}
{#{% for celestial in system.celestial_set.all() %}#}
{#<div class="cards">#}
{#    <div class="block" id="elmback1">#}
{##}
{#        <img src="" alt=""/>#}
{#        <figcaption>#}
{#            {{ celestial.errors }}#}
{#            {{ celestial.label_tag }}#}
{##}
{#        </figcaption>#}
{#    </div>#}
{##}
{#    {% for f in fils %}#}
{##}
{#    <div class="block" id="elmback2">#}
{##}
{#        <img src="" alt=""/>#}
{#        <figcaption>#}
{#            {{ f.errors }}#}
{#            {{ f.label_tag }} {{ f }}#}
{#        </figcaption>#}
{#    </div>#}
{#    {% endfor %}#}
{#</div>#}
{#{% endfor %}#}

<div class="infosyst">
    <p></p>
</div>

appsystem/templates/system_list.html
{% load static %}

<html lang="">

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}" />
    <meta charset="utf-8" />
    <title>Elite Dangerous System </title>
</head>

<body>
	{% block header %}
			<header>
				<div id="logo">
				    <a href="{% url 'home' %}"><img src="{% static 'elite.png' %}" alt="" /></a>
				</div>
			</header>
		{% endblock %}
 {% block body %}
 {% block contenu %}
	<div id='slider'>
    <div class="container">
	 {% for system in systems %}
		 <input checked id='slide-{{ system.id }}' name='slides' type='radio'>
		 <a href="{% url 'systems' system.id %}" class='slide-item'>
			 <div class="slide-content">
				 <h3>{{ system.name }}</h3>
				 <p>Cliquer pour en savoir plus</p>
			 </div>
			 <div class="slide-img"><img src="/static/system{{ system.id }}.png" alt=""></div>
		 </a>
		 <nav class='slide-nav'>
			 {% if not forloop.first %}
				 <label class='slide-prev' for='slide-1'></label>
			 {% endif %}
			 {% if not forloop.last %}
				 <label class='slide-next' for='slide-2'></label>
			 {% endif %}
		 </nav>
	 {% endfor %}
	 <nav class='slide-dots'>
		 {% for system in systems %}
			 <label class='slide-dot' for='slide-{{ system.id }}'></label>
		 {% endfor %}
	 </nav>
 </div>
    </div>
<div class="info">
 <h2>Tous les systèmes</h2>
	<table>
		<thead>
			<tr>
				<th>ID</th>
				<th>Nom</th>
				<th>Sous-systèmes</th>
				<th>Astres</th>

			</tr>
		</thead>
		<tbody>
			{% for system in systems %}
				<tr>
					<td> {{ system.id }} </td>
					<td> {{ system.name }} </td>
					<td> {{ system.sub_systems_count }} </td>
					<td> {{ system.astronomical_bodies_count }} </td>
					<td> <a href="{% url 'systems' system.id %}">Voir</a> </td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
{% endblock %}
     {% block footer %}
      <footer>
 <div id="colum.side">
     <table>
         <tr>
             <td><a href="{% url 'search' %}"><img src="{% static 'loupe.png' %}" alt=""></a></td>
         </tr>
         <tr>
             <td><a href="{% url 'choices_add' %}"><img src="{% static 'ajout.png' %}" alt=""></a></td>
         </tr>
     </table>
 </div>
    <table id="icones" style="margin: 0 auto;">
        <tr>
            <td align="center">
                <figure >
                    <a href ="https://www.facebook.com/EliteDangerousOfficial/?ref=page_internal"><img src="{% static 'facebook.png' %}" alt="Facebook" class="facebook" /></a>
                </figure>
            </td>

            <td align="center">
                <figure >
                    <a href ="https://www.instagram.com/elite.dangerous/"><img src="{% static 'insta.png' %}" alt="Instagram" href="#" class="instagram"/></a>
                </figure>
            </td>

            <td align="center">
                <figure>
                    <a href ="https://forums.frontier.co.uk/showthread.php/164176-GalNet-RSS-Feed"><img src="{% static 'rss.png' %}" alt="RSS" href="#" class="rss"/></a>
                </figure>
            </td>
        </tr>
    </table>
     <br></br>
		<center><div id="connexion">
            <a href="{% url 'login' %}">Connexion</a>
            <a href="{% url 'sign_up' %}">Créer un compte</a>
        </div></center>
     <p id="bas">MNHN Company</p>
</footer>
{% endblock %}
{% endblock %}
</body>
</html>

appsystem/templates/validation.html
{% extends 'system_list.html.' %}

{% block body %}
						 <h1> {{message}}</h1>
						 <p> Pour retourner à l'accueil, cliquez <a href={% url 'home' %}>ici</a></p>
{% endblock %}